import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  NbBadgeModule,
  NbButtonModule,
  NbCardModule,
  NbCheckboxModule,
  NbContextMenuModule,
  NbDialogModule,
  NbFormFieldModule,
  NbIconModule,
  NbInputModule,
  NbLayoutModule,
  NbMenuModule,
  NbSearchModule,
  NbSelectModule,
  NbSidebarModule,
  NbStepperModule,
  NbTagModule,
  NbTimepickerModule,
  NbUserModule,
} from '@nebular/theme';
import { NbEvaIconsModule } from '@nebular/eva-icons';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { ToastrModule } from 'ngx-toastr';
import { NotifierModule } from 'angular-notifier';
import { NgxSpinnerModule } from 'ngx-spinner';
import { AngularEditorModule } from '@kolkov/angular-editor';
import { NgpImagePickerModule } from 'ngp-image-picker';

@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    NbLayoutModule,
    NbEvaIconsModule,
    NbCardModule,
    NbFormFieldModule,
    NbIconModule,
    NbStepperModule,
    ToastrModule.forRoot({
      timeOut: 10000,
      positionClass: 'toast-bottom-right',
      preventDuplicates: true,
    }),
    NotifierModule.withConfig({}),
    NbSidebarModule.forRoot(),
    NbLayoutModule,
    NbEvaIconsModule,
    NbCardModule,
    NbFormFieldModule,
    NbIconModule,
    NbStepperModule,
    ReactiveFormsModule,
    NbButtonModule,
    FormsModule,
    NbInputModule,
    NbCardModule,
    NbMenuModule.forRoot(),
    NbDialogModule.forRoot(),
    NbUserModule,
    NbContextMenuModule,
    NbTimepickerModule.forRoot(),
    NgxSpinnerModule,
    NbSelectModule,
    NbTagModule,
    AngularEditorModule,
    NbCheckboxModule,
    NgpImagePickerModule,
  ],
  exports: [
    ReactiveFormsModule,
    NbLayoutModule,
    NbSidebarModule,
    NbEvaIconsModule,
    NbCardModule,
    NbFormFieldModule,
    NbIconModule,
    NbStepperModule,
    ReactiveFormsModule,
    FormsModule,
    NbButtonModule,
    NbInputModule,
    NbSearchModule,
    NbMenuModule,
    NbBadgeModule,
    NbUserModule,
    NbTimepickerModule,
    NbContextMenuModule,
    NgxSpinnerModule,
    NbSelectModule,
    NbTagModule,
    AngularEditorModule,
    NbCheckboxModule,
    NgpImagePickerModule,
  ],
})
export class SharedModule {}
